services:
  app:
    build: .
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    restart: always
    ports:
      - "20717:20717"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
